import frappe
import json
from frappe.model.naming import make_autoname

DEFAULT_SELLING_PRICE_LIST = "Venta estándar"


def expected_selling_price_list_for_seguro(ars):
	return ars or DEFAULT_SELLING_PRICE_LIST


@frappe.whitelist()
def fix_draft_seguro_selling_price_list(dry_run=False):
	"""Corrige selling_price_list en borradores de Clientes Seguros."""
	dry_run = frappe.parse_json(dry_run)
	fixed = []

	for inv in _get_mismatched_draft_seguro_invoices():
		expected = inv.expected_selling_price_list
		currency = frappe.db.get_value("Price List", expected, "currency")

		row = {
			"name": inv.name,
			"customer": inv.customer,
			"ars": inv.ars,
			"from": inv.selling_price_list,
			"to": expected,
		}
		fixed.append(row)

		if dry_run:
			continue

		frappe.db.set_value(
			"Sales Invoice",
			inv.name,
			{
				"selling_price_list": expected,
				"price_list_currency": currency,
			},
			update_modified=True,
		)

	if not dry_run and fixed:
		frappe.db.commit()

	return {
		"dry_run": dry_run,
		"count": len(fixed),
		"invoices": fixed,
	}


def _get_mismatched_draft_seguro_invoices():
	return frappe.db.sql(
		"""
		SELECT
			si.name,
			si.customer,
			COALESCE(NULLIF(si.ars, ''), NULLIF(c.ars, '')) AS ars,
			si.selling_price_list,
			COALESCE(NULLIF(si.ars, ''), NULLIF(c.ars, ''), %(default)s) AS expected_selling_price_list
		FROM `tabSales Invoice` si
		LEFT JOIN `tabCustomer` c ON c.name = si.customer
		WHERE si.docstatus = 0
		  AND si.tipo_de_factura = 'Clientes Seguros'
		  AND si.selling_price_list != COALESCE(NULLIF(si.ars, ''), NULLIF(c.ars, ''), %(default)s)
		ORDER BY si.modified DESC
		""",
		{"default": DEFAULT_SELLING_PRICE_LIST},
		as_dict=True,
	)

def autoname(self, event):
	self.name = make_autoname("FACT-.#####")
	# Only fill ncf via naming_series as a last-resort fallback when dgii's
	# before_insert did not set one. The previous "or self.is_return" branch
	# overwrote the correct e-CF NCF (E34...) generated by dgii for returns
	# with the doc naming_series counter (SINV-YYYY-N), producing invalid NCFs
	# on credit notes.
	if not self.ncf:
		self.ncf = make_autoname(self.naming_series)

def on_submit(self, event):
	for item in self.items:
		for name in (item.paid_sales_invoices or "").split(","):
			if not name: return

			doc = frappe.get_doc("Sales Invoice", name)
			# update payment_status [PAID|PARTIALLY PAID|UNPAID]
			doc.payment_status = "UNPAID" if self.get("is_return") else "PAID"

			doc.db_update()

	frappe.db.commit()

@frappe.whitelist()
def update_personal_info(self):
	data = json.loads(self) 
	inv = frappe.get_doc(data.get('doctype'), data.get('name'))
	cust = frappe.get_doc("Customer", inv.customer)
	inv.update({
		"nss": cust.nss,
		"tax_id": cust.tax_id,
		"ars": cust.ars
	})
	inv.db_update()
	frappe.db.commit()

def on_cancel(self, event):
	for item in self.items:
		for name in (item.paid_sales_invoices or "").split(","):
			if not name: return

			doc = frappe.get_doc("Sales Invoice", name)
			# update payment_status [PAID|PARTIALLY PAID|UNPAID]
			doc.payment_status = "PAID" if self.get("is_return") else "UNPAID"

			doc.db_update()

	frappe.db.commit()

